name: pinpoint
description: "A new Flutter project."

publish_to: 'none'

version: 1.2.5+15

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_displaymode: ^0.7.0
  flutter_dotenv: ^6.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5
  go_router: ^17.0.0
  animate_do: ^4.0.1
  material_symbols_icons: ^4.2801.1
  stylish_bottom_bar: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  get_it: ^9.0.5
  skeletonizer: ^2.0.1
  choice: ^2.3.2
  record: ^6.0.0
  audioplayers: ^6.1.2
  path_provider: ^2.1.5
  avatar_glow: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  intl: 0.20.2
  toastification: ^3.0.0
  drift_db_viewer: ^2.1.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  delightful_toast: ^1.1.0
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  local_auth: ^3.0.0
  encrypt: ^5.0.1
  google_mlkit_text_recognition: ^0.15.0
  speech_to_text: ^7.1.0
  logger: ^2.4.0
  share_plus: ^12.0.1
  printing: ^5.11.1
  file_picker: ^10.2.1
  painter: ^2.0.0
  pdf: ^3.10.8
  flutter_secure_storage: ^10.0.0-beta.1
  flutter_exit_app: ^2.0.0
  flutter_timezone: ^5.0.1
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.4.0+6
  in_app_update: ^4.2.3
  dio: ^5.7.0
  package_info_plus: ^9.0.0
  device_info_plus: ^12.2.0
  connectivity_plus: ^6.1.1
  provider: ^6.1.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  firebase_messaging: ^16.0.4
  async_queue: ^2.0.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  fleather: ^1.15.0
  parchment: ^1.15.0
  parchment_delta: ^1.0.0
  tutorial_coach_mark: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.24.0
  build_runner: ^2.4.14

flutter_plugins:
  logger:
    platforms:
      android:
      ios:
      linux:
      macos:
      web:
      windows:

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/legal/
